test_anagram (__main__.TestExercice) ... ok
test_doubles (__main__.TestExercice) ... ok
test_frequence (__main__.TestExercice) ... ERROR
test_grades (__main__.TestExercice) ... ok
test_order (__main__.TestExercice) ... ok

======================================================================
ERROR: test_frequence (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 77, in test_frequence
    output = [exercice.frequence(s) for s in sentences]
  File "test_exercice.py", line 77, in <listcomp>
    output = [exercice.frequence(s) for s in sentences]
  File "/home/runner/work/c04-ch6-exercices-ghalich/c04-ch6-exercices-ghalich/exercice.py", line 67, in frequence
    occ_dict = occ_dict.get(i, 0) + 1
AttributeError: 'int' object has no attribute 'get'

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=1)
